export const privateRoutePath = Object.freeze({
  base: "/",
  dashboard: "/",
  userManagement: "/usermanagement",
  userCreation: "/usermanagement/user-creation",
  clientManagement: "/usermanagement/client",
  roleSetup: "/usermanagement/role",
  branchSetup: "/usermanagement/branch",
  permissionSetup: "/usermanagement/role/permission/:roleId",
  rolePrivilegeSetup: "/usermanagement/role-privilege/:id",
  privilegeSetupTest: "/usermanagement/privilege",
  schedulePasswordReset: "/usermanagement/schedule-password-reset",
  moduleSetupTest: "/usermanagement/module",
  addUser: "/usermanagement/client/add-user/:id",
  userRegistration: "/usermanagement/user-registration",
  screenModuleSetup: "/screen-module-setup",
  screenSetup: "/screen-module-setup/screen",
  privilegeSetup: "/screen-module-setup/privilege",
  moduleSetup: "/screen-module-setup/module",
});
