export const SCREEN = Object.freeze({
  USERMANAGEMENT: "USER-MANAGEMENT",
  SCREENMODULEPRIVILEGE: "SCREEN-MODULE-PRIVILEGE",
  MASTERCONFIGURATION: "MASTER-CONFIGURATION",
  TRANSACTION: "TRANSACTION",
  BRANCH: "BRANCH",
  PARTNER: "PARTNER",
});
